FROM python:3.8

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

# Kopioi entrypoint.sh ja tee se suoritettavaksi
COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

# Määritä entrypoint.sh suoritettavaksi
ENTRYPOINT ["entrypoint.sh"]

