# Generated by Django 4.2.1 on 2023-09-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Opettaja'), ('student', 'Oppilas'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
