# Generated by Django 4.2.1 on 2023-09-28 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_course_tutorialcategory_usercourse_tutorial_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
    ]
