# Generated by Django 4.2.1 on 2023-10-01 11:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_tutorial_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Prerequisites',
            field=models.TextField(default='Ei esitietoja'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
