# Generated by Django 4.2.1 on 2023-10-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_course_prerequisites_alter_tutorial_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Prerequisites',
            new_name='prerequisites',
        ),
    ]
