# Generated by Django 4.2.1 on 2023-10-11 23:01

from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_taskcategory_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='editor_theme',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, default=main_app.models.get_default_task_category, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.taskcategory'),
        ),
    ]
