# Generated by Django 4.2.1 on 2023-11-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_course_courselogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorialLogo',
            field=models.ImageField(default='tuto_logos/no_logo.png', upload_to='tuto_logos/'),
        ),
    ]
