# Generated by Django 4.2.1 on 2023-11-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_tutorial_tutoriallogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorialLogo',
            field=models.ImageField(default='tuto_logos/default_tuto.png', upload_to='tuto_logos/'),
        ),
    ]
