# Generated by Django 4.1 on 2024-02-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_course_video_url_task_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_all_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
