# Generated by Django 4.1 on 2024-02-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Javascript', 'JavaScript'), ('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('Pseudo', 'Pseudo')], default='Python', max_length=20),
        ),
    ]
