# Generated by Django 4.1 on 2024-03-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_task_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Javascript', 'JavaScript'), ('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('Pseudo', 'Pseudo'), ('Vaativuuslakelmat', 'vaativuuslaskelmat')], default='Python', max_length=20),
        ),
    ]
