# Generated by Django 4.1 on 2024-03-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_task_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='run_tests',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tester', 'Testaaja'), ('teacher', 'Opettaja'), ('student', 'Oppilas'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
