# Generated by Django 4.1 on 2024-03-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_task_is_hidden_task_run_tests_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_test_state',
            field=models.BooleanField(default=False),
        ),
    ]
