# Generated by Django 4.1 on 2024-03-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='tutorials',
            field=models.ManyToManyField(blank=True, related_name='courses', to='main_app.tutorial'),
        ),
    ]
