# Generated by Django 4.1 on 2024-03-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_remove_tutorial_course_course_tutorials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('aloittelija', 'Aloittelija'), ('harjoittelija', 'Harjoittelija'), ('kehittäjä', 'Kehittäjä'), ('mestari', 'Mestari'), ('guru', 'Guru')], default='aloittelija', max_length=20),
        ),
    ]
