# Generated by Django 4.1 on 2024-03-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_alter_task_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Taso'),
        ),
        migrations.AddField(
            model_name='user',
            name='level_icon',
            field=models.ImageField(blank=True, null=True, upload_to='user_level_icons/', verbose_name='Tason ikoni'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Pisteet'),
        ),
    ]
