# Generated by Django 4.1 on 2024-03-31 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_user_level_user_level_icon_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level_icon',
        ),
    ]
