# Generated by Django 4.1 on 2024-03-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_alter_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=100, verbose_name='Pisteet'),
        ),
    ]
