# Generated by Django 4.2.16 on 2025-01-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_lambdausage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lambdausage',
            name='cost_usd',
        ),
        migrations.RemoveField(
            model_name='lambdausage',
            name='execution_time_ms',
        ),
        migrations.RemoveField(
            model_name='lambdausage',
            name='memory_used_mb',
        ),
    ]
